[custom]
custom_proxy_group=🚀 全局 Select`select`[]♻️ 全局 Auto`[]DIRECT`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select
custom_proxy_group=♻️ 全局 Auto`url-test`^(?!.*(?i)(隧道|tunnel|vpn|wireguard)).*$`http://www.gstatic.com/generate_204`300
custom_proxy_group=🍙 日本Select`select`[]🍙 日本Auto`[]DIRECT`(日本|jp)
custom_proxy_group=🍙 日本Auto`url-test`(日本|jp)`http://www.gstatic.com/generate_204`300
custom_proxy_group=👌 韩国Select`select`[]👌 韩国Auto`[]DIRECT`(韩国|kr)
custom_proxy_group=👌 韩国Auto`url-test`(韩国|kr)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🌃 港台Select`select`[]🌃 港台Auto`[]DIRECT`(香港|hk|台湾|tw)
custom_proxy_group=🌃 港台Auto`url-test`(香港|hk|台湾|tw)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🗽 美国Select`select`[]🗽 美国Auto`[]DIRECT`(美国|us)
custom_proxy_group=🗽 美国Auto`url-test`(美国|us)`http://www.gstatic.com/generate_204`300
custom_proxy_group=🍛 新加坡Select`select`[]🍛 新加坡Auto`[]DIRECT`(新加坡|sg)
custom_proxy_group=🍛 新加坡Auto`url-test`(新加坡|sg)`http://www.gstatic.com/generate_204`300
custom_proxy_group=💂‍♂ 英国Select`select`[]💂‍♂ 英国Auto`[]DIRECT`(英国|en|tr)
custom_proxy_group=💂‍♂ 英国Auto`url-test`(英国|en|tr)`http://www.gstatic.com/generate_204`300

custom_proxy_group=🧠 AI`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]
custom_proxy_group=🤖 OpenAI`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]🎙 海外直播
custom_proxy_group=▶ YouTube`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]🎙 海外直播
custom_proxy_group=🎬 Netflix`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select
custom_proxy_group=🍎 Apple`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]DIRECT
custom_proxy_group=🎮 Steam`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]DIRECT
custom_proxy_group=🎙 海外直播`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`(自建|自定义|custom)`[]DIRECT
custom_proxy_group=🏠 内网穿透-家庭`select`[]DIRECT`.*(?i)(隧道|tunnel|vpn|wireguard).*
custom_proxy_group=🏢 内网穿透-工作`select`[]DIRECT`.*(?i)(隧道|tunnel|vpn|wireguard).*
custom_proxy_group=🚫 屏蔽广告`select`[]REJECT`[]DIRECT

custom_proxy_group=🐟 漏网之鱼`select`[]🚀 全局 Select`[]🍙 日本Select`[]👌 韩国Select`[]🌃 港台Select`[]🗽 美国Select`[]🍛 新加坡Select`[]💂‍♂ 英国Select`[]DIRECT

;Options for custom rulesets
enable_rule_generator=true
overwrite_original_rules=true

;======== 个性化（放在最前，优先级最高） =======
; YouTube
ruleset=▶ YouTube,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=▶ YouTube,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/YouTubeMusic.list

; AI
; 分为默认AI和OpenAI两个不同的策略组，Google默认走默认A策略组（一般选日本），OpenAI选新加坡
ruleset=🤖 OpenAI,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🧠 AI,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Google.list
ruleset=🧠 AI,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=🧠 AI,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Gemini.list
ruleset=🧠 AI,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Claude.list

;======== 手动Only =======
; 日本Only
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/JapanOnly.list

; 港台Only
ruleset=🌃 港台Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/HongKongOnly.list

; 直连Only
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/DirectOnly.list

;======== 内网穿透 =======
; 内网穿透
ruleset=🏠 内网穿透-家庭,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/LocalServerHome.list
ruleset=🏢 内网穿透-工作,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/LocalServerWork.list

;======== 广告屏蔽 =======
ruleset=🚫 屏蔽广告,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/BanAD.list
ruleset=🚫 屏蔽广告,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=🚫 屏蔽广告,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/BanEasyListChina.list

;======== 日本 =======
; Pixiv
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Pixiv.list
; NicoNico
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Niconico.list
; DMM
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Dmm.list
; Claude
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Claude.list

;======== 游戏 =======
; Steam
ruleset=🎮 Steam,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset= DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/SteamCN.list
; Discord
ruleset=🚀 全局 Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Discord.list
; Nintendo
ruleset=🚀 全局 Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Nintendo.list

;======== 影音 =======

; Apple
ruleset=🍎 Apple,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Apple.list
ruleset=🍎 Apple,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/AppleTV.list

; BiliBili
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Bilibili.list

; Netflix
ruleset=🎬 Netflix,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Netflix.list

; Porn
ruleset=🍙 日本Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Ruleset/Porn.list

;======== 直连 =======
; 中国域名
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/ChinaDomain.list
; 私有网络
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/LocalAreaNetwork.list
; 云服务厂商
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/ChinaCompanyIp.list
; 国内直连IP
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/ChinaIp.list
; 下载用
ruleset=DIRECT,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/Download.list
; GEOIP为中国
ruleset=DIRECT,[]GEOIP,CN

;======== 基础全局代理（必须放在后面，因为靠前的优先级高） =======
; GFW
ruleset=🚀 全局 Select,https://github.mirror.acgstyle.net/SuperCarrado/ACL4SSR/master/Clash/ProxyLite.list

;======== 漏网之鱼 =======
ruleset=🐟 漏网之鱼,[]FINAL


;Options for custom base configuration file
;clash_rule_base=base/forcerule.yml
;surge_rule_base=base/surge.conf
;surfboard_rule_base=base/surfboard.conf
;mellow_rule_base=base/mellow.conf
;quan_rule_base=base/quan.conf
;quanx_rule_base=base/quanx.conf
;loon_rule_base=base/loon.conf
;sssub_rule_base=base/shadowsocks_base.json
;singbox_rule_base=base/singbox.json

;Options for renaming nodes
;rename=Test-(.*?)-(.*?)-(.*?)\((.*?)\)@\1\4x测试线路_自\2到\3
;rename=\(?((x|X)?(\d+)(\.?\d+)?)((\s?倍率?)|(x|X))\)?@$1x

;Options for adding emojis
;add_emoji=true
;remove_old_emoji=true
;emoji=(流量|时间|应急),🏳️‍🌈
;emoji=阿根廷,🇦🇷

;Options for filtering nodes
;include_remarks=
;exclude_remarks=

;[template]
;;variables in the local scope
;clash.dns.port=5353
